export const MEMBER_STATE = {
  MEMBERS: `MEMBERS`
}

export const MEMBER_MUTATION = {
  SET_MEMBER: `SET_MEMBER`,
  ADD_MEMBER: `ADD_MEMBER`
}

export const MEMBER_ACTION = {
  FETCH_MEMBER: `FETCH_MEMBER`,
  CREATE_MEMBER: `CREATE_MEMBER`
}
