export const PURCHASE_STATE = {
  PURCHASES: `PURCHASES`
}

export const PURCHASE_MUTATION = {
  SET_PURCHASE: `SET_PURCHASE`,
  ADD_PURCHASE: `ADD_PURCHASE`
}

export const PURCHASE_ACTION = {
  FETCH_PURCHASE: `FETCH_PURCHASE`,
  CREATE_PURCHASE: `CREATE_PURCHASE`
}
